version: '3.1'

services:
   db_mysql:
      container_name: mysql
      image: mysql
      ports:
         - "3311:3306"
      restart: always
      environment:
         MYSQL_ROOT_USER: root
         MYSQL_ROOT_PASSWORD: root1q2w3e4r
         MYSQL_DATABASE: manufactorymate
         MYSQL_USER: user_spring
         MYSQL_PASSWORD: spring123

      volumes:
         - ./MySQL/db:/var/lib/mysql

   phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
         - "80:80"
      environment:
         PMA_HOST: db_mysql
      depends_on:
         - db_mysql

#   Eureka:
#      image: eureka-server
#      ports:
#         - 8761:8761
#      restart: always