server:
  port: 8086
spring:
  application:
    name: Product-Server
  datasource:
    url: jdbc:mysql://localhost:3311/manufactorymate
    username: user_spring
    password: spring123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/