server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: scheduling-server
          uri: http://scheduling-server:80
          predicates:
            - Path=/scheduling/**
          filters:
            - StripPrefix=1
        - id: product-server
          uri: http://product-server:80
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: produce-server
          uri: http://produce-server:80
          predicates:
            - Path=/produce/**
          filters:
            - StripPrefix=1
        - id: data-service-server
          uri: http://data-service:80
          predicates:
            - Path=/dataservice/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/